name: Fetching Data
on:
  schedule:
    - cron: "00 23 * * *"
  workflow_dispatch:
  
jobs:
  Fetch-Bus-Data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
            architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch data
        run: |

          python pricewatch.py
          
          
          
      - name: Update data files
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
              pricewatch_itemlist.json
              
            commit-msg: Update resources
            github-token: ${{ secrets.ACCESS_TOKEN }}
            branch: main
